#线上环境是怎么样就怎么样填
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #线上数据库url
    url: jdbc:mysql://线上数据库地址:3306/zhaotongxingzhe
    username: root
    password: 密码
  redis:
    port: 6379
    host: 线上redis地址
    database: 0
    password: 密码
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
